baseurl = "https://writing-matiasandina.netlify.com/"
title = "Writing"
author = "Matias Andina"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "UNPUBLISHED"]
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Matias Andina"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://matiasandina.netlify.com/about/"
    weight = 1
[[menu.main]]
    name = "Contribute"
    url  = "/contribute"
    weight = 2
[[menu.main]]
	name       = "Contact"
	url        = "/contact"
	weight     = 3

[taxonomies]
  tag      = "tags"